### ISSUE TITLE
Modern buildsystem: first attempt at meson

### ISSUE THREAD

**Issue by dragetd** [colindean/optar#12]
Yes, this is kind of unnecessary and still incomplete. But I wanted to learn Meson and I thought optar would be a nice mini-project to try it on.

Since I did not find a common chat platform to bother you on there, I opened this issue to show you my first attempt: https://github.com/dragetd/optar/tree/draget-make-patch

Any thoughts on this? :D

Perfectly okay if you have no interest, then I will continue my experiments on my fork. :)

**Comment by colindean** [comment]
The chief problem I have with Meson is that it’s not as available and widely understood as Make or any of the other popular make alternatives, like CMake, Basil, etc. Sell me more on Meson and I might go for it.

I like the organization of the source that you’ve done.

**Comment by dragetd** [comment]
I am with you on that one. :P Just thought I'd show you anyway.
