### ISSUE TITLE
Python, JS and Go version of the software

### ISSUE THREAD

**Issue by DonaldTsang** [colindean/optar#15]
Objective C is being deprecated over Swift, so if it is possible, please have these versions ready.
- [ ] Python (a good scripting language)
- [ ] JS (for web-based implementation)
- [ ] Go (A Java/C#/Swift/Kotlin replacement)

**Comment by colindean** [comment]
Unfortunately, this is extremely unlikely to happen. If anything, I'd consider a port to Rust but I'm not the original author of `optar` and would have some studying to do to understand the underpinnings.

Moreover, Objective-C isn't going away, it's just not the preferred language for new projects. Also, this project is written in C, not Objective-C.

**Comment by DonaldTsang** [comment]
@colindean so the Objective C is a wrapper? In that case is it possible to also have Python/JS/Go as another wrapper?

**Comment by colindean** [comment]
There is no Objective-C in this code base.

I am unlikely to implement library code to make this easy to use from other languages through FFI. I would certainly accept pull requests for such, though.

**Comment by DonaldTsang** [comment]
@colindean wait, then what are these? https://github.com/colindean/optar/search?l=objective-c

**Comment by colindean** [comment]
They're regular C header files that are misidentified as Objective-C.

**Comment by DonaldTsang** [comment]
@colindean are there any way of fixing it, maybe report back to dev team of GitHub?

**Comment by colindean** [comment]
You are welcome and encouraged to report it.
