### ISSUE TITLE
Technical explanation of how it works

### ISSUE THREAD

**Issue by lf94** [colindean/optar#6]
I and many others would greatly appreciate it.

My biggest concern is being able to recreate the source code if ever I need to in the future, but I need to understand be able to easily understand what techniques are employed here :smile: 

Thank you!

I would also like to know how you came up with using Golay codes.

**Comment by colindean** [comment]
Note that I am not the original author of this. I merely archived it
here because it was very difficult for me to find the source code.
I have never really dug into the implementation details, only used it
as a tool.

**Comment by lf94** [comment]
Ah. Guess I have some emailing to do. Thanks :+1:
